language: php

php:
  - 7.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update

install: composer update

script: ./vendor/bin/phpunit -v --coverage-text
